from nginx

ADD mantisbt-2.24.2.tar.gz /var/www/
RUN rm -rf /var/www/html && \
    mv /var/www/mantisbt* /var/www/html && \
    chown -R www-data:www-data /var/www/html && \
    chmod -R a+rx /var/www/html

ADD nginx-mantis.conf /etc/nginx/conf.d/default.conf


